server:
    port: 8080
    #compression:
    #    enabled: true

    error:
        whitelabel:
            enabled: false

spring:
    # thymeleaf:
    #     prefix: classpath:/templates/
    #     suffix: .html

    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:~/todo
        username: sa
        password:
    h2:
        console: 
            enabled: true
    
    jpa:
        database: h2
        show-sql: true
        #hibernate:
        #    ddl-auto: create-drop
        database-platform: org.hibernate.dialect.H2Dialect

    sql:
       init:
        mode: always
        
jwt:
    secret: todo-secret

    # Configuración del nivel de registro (DEBUG, INFO, WARN, ERROR)
logging:
    level:
        root: INFO
    